services:
  dev:
    image: ryanmillard/img2num-dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: img2num-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:cached
      - pnpm-store:/pnpm
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
    ports:
      - "5173:5173" # Vite dev
      - "4173:4173" # Vite preview
      - "3000:3000" # Docusaurus dev
    stdin_open: true
    tty: true

volumes:
  pnpm-store:
