name: Build C & C++

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-wasm:
    name: Build WASM (bindings/js)
    runs-on: ubuntu-latest
    container:
      image: ryanmillard/img2num-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run emcmake
        run: emcmake cmake -B build-wasm/ .

      - name: Build using Emscripten
        run: cmake --build build-wasm/

      - name: Upload WASM build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: wasm-build
          path: packages/js/build-wasm/

  build-c-cpp:
    name: Build C & C++
    runs-on: ubuntu-latest
    container:
      image: ryanmillard/img2num-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run cmake
        run: cmake -B build-c-cpp/ .

      - name: Build C/C++
        run: cmake --build build-c-cpp/

      - name: Upload C/C++ build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-c-cpp
          path: build-c-cpp/
